"""initial tables

Revision ID: 620d2b422b19
Revises: 
Create Date: 2026-03-20 11:45:01.297365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620d2b422b19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_class_class_id'), 'class', ['class_id'], unique=False)
    op.create_table('constraint',
    sa.Column('constraint_id', sa.Integer(), nullable=False),
    sa.Column('constraint_name', sa.String(), nullable=False),
    sa.Column('constraint_type', sa.String(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('constraint_id')
    )
    op.create_index(op.f('ix_constraint_constraint_id'), 'constraint', ['constraint_id'], unique=False)
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_room_room_id'), 'room', ['room_id'], unique=False)
    op.create_table('teacher',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(), nullable=False),
    sa.Column('max_periods_per_day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_index(op.f('ix_teacher_teacher_id'), 'teacher', ['teacher_id'], unique=False)
    op.create_table('timeslot',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_index(op.f('ix_timeslot_slot_id'), 'timeslot', ['slot_id'], unique=False)
    op.create_table('subject',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('periods_per_week', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_subject_subject_id'), 'subject', ['subject_id'], unique=False)
    op.create_table('teacher_availability',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['timeslot.slot_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'slot_id')
    )
    op.create_table('teacher_subject',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id')
    )
    op.create_table('timetable',
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['timeslot.slot_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    op.create_index(op.f('ix_timetable_timetable_id'), 'timetable', ['timetable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_timetable_id'), table_name='timetable')
    op.drop_table('timetable')
    op.drop_table('teacher_subject')
    op.drop_table('teacher_availability')
    op.drop_index(op.f('ix_subject_subject_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_timeslot_slot_id'), table_name='timeslot')
    op.drop_table('timeslot')
    op.drop_index(op.f('ix_teacher_teacher_id'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_room_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_constraint_constraint_id'), table_name='constraint')
    op.drop_table('constraint')
    op.drop_index(op.f('ix_class_class_id'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
